docker:
    path: .
id: 4696a097-6653-41d0-baef-96b06f473fc6
ide:
    filename: ide.yaml
name: capstonellm-laurent
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: ""
version: "0.3"
workflows:
    path: dags
    version: "3"
